// Mocks generated by Mockito 5.4.6 from annotations
// in cba2026/test/unit/call_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cba2026/services/call_service.dart' as _i2;
import 'package:cba2026/services/transcript_service.dart' as _i4;
import 'package:elevenlabs_agents/elevenlabs_agents.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CallService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCallService extends _i1.Mock implements _i2.CallService {
  @override
  _i2.CallState get callState =>
      (super.noSuchMethod(
            Invocation.getter(#callState),
            returnValue: _i2.CallState.idle,
            returnValueForMissingStub: _i2.CallState.idle,
          )
          as _i2.CallState);

  @override
  set onStateChanged(void Function(_i2.CallState)? value) => super.noSuchMethod(
    Invocation.setter(#onStateChanged, value),
    returnValueForMissingStub: null,
  );

  @override
  set onModeChanged(void Function(_i3.ConversationMode)? value) =>
      super.noSuchMethod(
        Invocation.setter(#onModeChanged, value),
        returnValueForMissingStub: null,
      );

  @override
  void setTranscriptService(_i4.TranscriptService? service) =>
      super.noSuchMethod(
        Invocation.method(#setTranscriptService, [service]),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> startCall() =>
      (super.noSuchMethod(
            Invocation.method(#startCall, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> endCall() =>
      (super.noSuchMethod(
            Invocation.method(#endCall, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void resetState() => super.noSuchMethod(
    Invocation.method(#resetState, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
