// Mocks generated by Mockito 5.4.6 from annotations
// in cba2026/test/integration/call_session_lifecycle_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:cba2026/services/logger_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LoggerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoggerService extends _i1.Mock implements _i2.LoggerService {
  @override
  void logCallStart({required String? sessionId}) => super.noSuchMethod(
    Invocation.method(#logCallStart, [], {#sessionId: sessionId}),
    returnValueForMissingStub: null,
  );

  @override
  void logCallEnd({required String? sessionId}) => super.noSuchMethod(
    Invocation.method(#logCallEnd, [], {#sessionId: sessionId}),
    returnValueForMissingStub: null,
  );

  @override
  void logCallError({required String? sessionId, required String? error}) =>
      super.noSuchMethod(
        Invocation.method(#logCallError, [], {
          #sessionId: sessionId,
          #error: error,
        }),
        returnValueForMissingStub: null,
      );

  @override
  void logTurnEvent({
    required String? sessionId,
    required int? turnNumber,
    required String? speaker,
  }) => super.noSuchMethod(
    Invocation.method(#logTurnEvent, [], {
      #sessionId: sessionId,
      #turnNumber: turnNumber,
      #speaker: speaker,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void logReconnectionAttempt({
    required String? sessionId,
    required int? attemptNumber,
  }) => super.noSuchMethod(
    Invocation.method(#logReconnectionAttempt, [], {
      #sessionId: sessionId,
      #attemptNumber: attemptNumber,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void logStatusChange({required String? sessionId, required String? status}) =>
      super.noSuchMethod(
        Invocation.method(#logStatusChange, [], {
          #sessionId: sessionId,
          #status: status,
        }),
        returnValueForMissingStub: null,
      );

  @override
  void logModeChange({required String? sessionId, required String? mode}) =>
      super.noSuchMethod(
        Invocation.method(#logModeChange, [], {
          #sessionId: sessionId,
          #mode: mode,
        }),
        returnValueForMissingStub: null,
      );
}
